Issue 33: Added code examples to api-documentation
openearthplatforminitiative/weather-api pull request #10
Opened 2023-12-08 12:28 UTC by kstigen

2023-12-08 14:48 UTC, dymbe requested changes
Looks good! I did some things a bit differently in my PR, you should take a look at it so we can agree on how we want to do this on all APIs
https://github.com/openearthplatforminitiative/geocoder-api/pull/10/files

2023-12-08 14:48 UTC, dymbe commented on weather_api/__main__.py
>      api = FastAPI(
```python
If you want the doc to have a favicon too you need to create your own `/redoc`-endpoint:

app = FastAPI(
    lifespan=lifespan,
    root_path=settings.api_root_path,
    redoc_url=None,
)


@app.get("/redoc", include_in_schema=False)
def redoc():
    return get_redoc_html(
        openapi_url="/openapi.json",
        title="Geocoder API",
        redoc_favicon_url="https://www.openepi.io/favicon.ico",
    )

2023-12-08 14:59 UTC, dymbe commented on weather_api/openapi/openapi.py
> +                                api_endpoint=route.path,
Maybe the files can be made a bit simpler if you concatenate the URL here, and only pass in a single variable?

2023-12-11 07:55 UTC, kstigen commented on weather_api/config.py
> +    def public_url(self):
Can call it exposed_url or something like that

2023-12-11 13:33 UTC, merged