28 expose apis from met
openearthplatforminitiative/weather-api pull request #3
Opened 2023-10-18 07:15 UTC by kstigen

2023-10-20 08:13 UTC, dymbe requested changes
Looks good overall, I just have a few suggestions

2023-10-20 08:13 UTC, dymbe commented on app/weather_api/services/met_service.py
> +        if (
Suggestion: would this be more clean if you split this up a bit? I.e.

```
response = requests.(f"{settings.met_api_url}/locationforecast/2.0/healthz")
if response.status_code == 200
    (....)
```

2023-10-20 08:13 UTC, dymbe commented on app/weather_api/services/met_service.py
> +import requests
Why are you using both aiohttp and requests? Preferable you should only use aiohttp (or another async-capable library, like httpx), as requests is not async

2023-10-20 08:13 UTC, dymbe commented on pyproject.toml
> +aiohttp = "^3.8.6"
If you do in fact want to use `requests`, you should also include it here

2023-10-20 08:14 UTC, dymbe commented on app/weather_api/routes/system_resources.py
> +@router.get("/")
Is this route neccessary?

2023-10-20 11:13 UTC, kstigen commented on app/weather_api/routes/system_resources.py
> +@router.get("/")
Nopes, will remove

2023-10-23 08:11 UTC, dymbe commented on app/weather_api/services/met_service.py
> +import requests
It seems like requests is not used anymore, if that's the case you should remove this import

2023-10-23 08:16 UTC, dymbe approved these changes
LGTM, PR is ready for merge if you fix that final comment

2023-10-23 08:24 UTC, merged